# Generated by Django 4.1.1 on 2022-09-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('1', 'Junior Developer'), ('2', 'Middle Developer'), ('3', 'Senior Developer'), ('4', 'Team Lead'), ('5', 'Director')], max_length=25)),
                ('date_of_receipt', models.DateField()),
                ('salary', models.IntegerField()),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttest.fortest')),
            ],
        ),
    ]
